# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.provision "file", source: "./bin/minirc.kubos", destination: "~/minirc.kubos"
  config.vm.provision "file", source: "./bin/kubos-usb.rules", destination: "~/kubos-usb.rules"
  config.vm.provision "file", source: "./bin/cargo_config", destination: "~/cargo_config"
  config.vm.provision "privileged",    type: "shell", path: "./script/privileged-provision.sh"
  config.vm.provision "non-privileged", type: "shell", path: "./script/non-privileged-provision.sh", privileged: false
  config.vm.provision "test",          type: "shell", privileged: false, path: "./script/provision-test.sh"
  config.vm.provision "pre-package",   type: "shell", path: "./script/pre-package.sh"
  config.vm.synced_folder ".", "/vagrant"

  #To mount a specific directory into your box uncomment the next line and change the following paths to match your host directory and a desired mount point in the box.
  #config.vm.synced_folder "/path/on/host", "/path/in/vagrant/box"
  #IMPORTANT: AFTER MODIFYING THIS FILE YOU MUST RUN `vagrant reload` FOR THESE CHANGES TO TAKE EFFECT IF THE BOX IS ALREADY RUNNING

  # Enable USB access
  usb_devs = [
    #FTDI Devices
    ['0x0403', '0x6001', 'FTDI']
  ]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.customize ['modifyvm', :id, '--usb', 'on']
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
    usb_devs.each do |dev|
      vb.customize ['usbfilter', 'add', '0', '--target', :id, '--vendorid', dev[0], '--productid', dev[1], '--name', dev[2]]
    end
  end
end
