# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "velocity42/xenial64"
  config.vm.provision "file", source: "./bin/minirc.kubos", destination: "~/minirc.kubos"
  config.vm.provision "file", source: "./bin/kubos-usb.rules", destination: "~/kubos-usb.rules"
  config.vm.provision "privileged",  type: "shell", path: "./script/privileged-provision.sh"
  config.vm.provision "pre-package", type: "shell", path: "./script/pre-package.sh"
  config.vm.provision "test", type: "shell", path: "./script/provision-test.sh"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
  end
end
